// One word per silent beat, so the set has to be big enough that a long turn
// never repeats itself into looking stuck. US spelling throughout, gerunds
// only, and each one names work the agent actually does — nothing that
// advertises guessing. The rare draws sit at the end: Argmaxing, the
// signature, then the jokes.
export const THINKING_WORDS = [
  "Brainstorming",
  "Disentangling",
  "Sanity-checking",
  "Theorizing",
  "Deciphering",
  "Synthesizing",
  "Deconstructing",
  "Distilling",
  "Reconciling",
  "Refining",
  "Calculating",
  "Thinking",
  "Computing",
  "Analyzing",
  "Philosophizing",
  "Reasoning",
  "Deducing",
  "Inferring",
  "Extrapolating",
  "Hypothesizing",
  "Deliberating",
  "Contemplating",
  "Dissecting",
  "Unpacking",
  "Parsing",
  "Triangulating",
  "Cross-referencing",
  "Correlating",
  "Diagnosing",
  "Investigating",
  "Excavating",
  "Spelunking",
  "Retracing",
  "Surveying",
  "Sleuthing",
  "Formulating",
  "Composing",
  "Drafting",
  "Assembling",
  "Consolidating",
  "Architecting",
  "Scrutinizing",
  "Second-guessing",
  "Stress-testing",
  "Interrogating",
  "Falsifying",
  "Auditing",
  "Verifying",
  "Optimizing",
  "Converging",
  "Approximating",
  "Quantifying",
  "Simulating",
  "Enumerating",
  "Backpropagating",
  "Condensing",
  "Sharpening",
  "Tightening",
  "Weighing",
  "Prioritizing",
  "Argmaxing",
  "Yak-shaving",
  "Tail-chasing",
  "Overthinking",
  "Gradient-descending"
] as const;
