import { Check, Copy, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState, type JSX } from "react";
import { errorMessage } from "../../../shared/error.js";
import type { RemoteStatus } from "../../../shared/types.js";
import { useCopyToClipboard } from "../../hooks/useCopyToClipboard.js";
import { SettingGroup, SettingNote, SettingRow, Toggle } from "./settingsPrimitives.js";

/**
 * Settings → Integrations → Remote access: pair a phone with the local
 * bridge (QR encodes the tailnet URL + token) and configure ntfy push.
 */
export function RemoteSettings(): JSX.Element {
  const [status, setStatus] = useState<RemoteStatus | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [portField, setPortField] = useState("");
  const [topicField, setTopicField] = useState("");
  const [note, setNote] = useState<{ kind: "saved" | "error"; message: string } | null>(null);
  const [busy, setBusy] = useState(false);

  const adoptStatus = useCallback((next: RemoteStatus): void => {
    setStatus(next);
    setPortField(String(next.port));
    setTopicField(next.ntfyTopic ?? "");
  }, []);

  const loadStatus = useCallback(async (): Promise<void> => {
    if (!window.argmax) {
      setLoadError("Open the Argmax desktop app to configure remote access.");
      return;
    }
    try {
      adoptStatus(await window.argmax.remote.getStatus());
      setLoadError(null);
    } catch (error) {
      setLoadError(errorMessage(error));
    }
  }, [adoptStatus]);

  useEffect(() => {
    void loadStatus();
  }, [loadStatus]);

  // `fields` defaults to the drafts, which is what "Save changes" commits. The
  // enable toggle passes the saved values instead: flipping the switch must not
  // silently commit a half-typed port or an ntfy topic the user never saved.
  const saveConfig = useCallback(
    async (enabled: boolean, fields?: { port: string; ntfyTopic: string }): Promise<void> => {
      if (!window.argmax || !status) return;
      const source = fields ?? { port: portField, ntfyTopic: topicField };
      const port = Number.parseInt(source.port, 10);
      if (!Number.isInteger(port) || port < 1024 || port > 65535) {
        setNote({ kind: "error", message: "Port must be between 1024 and 65535." });
        return;
      }
      setBusy(true);
      setNote(null);
      try {
        const next = await window.argmax.remote.setConfig({
          enabled,
          port,
          ntfyTopic: source.ntfyTopic
        });
        adoptStatus(next);
        setNote(
          next.enabled && !next.serving
            ? {
                kind: "error",
                message: `The bridge could not start on port ${next.port} — is something else using it?`
              }
            : { kind: "saved", message: "Saved." }
        );
      } catch (error) {
        setNote({ kind: "error", message: errorMessage(error) });
      } finally {
        setBusy(false);
      }
    },
    [adoptStatus, portField, status, topicField]
  );

  const sendTestNotification = useCallback(async (): Promise<void> => {
    if (!window.argmax) return;
    setBusy(true);
    setNote(null);
    try {
      await window.argmax.remote.testNotification();
      setNote({ kind: "saved", message: "Test notification sent — check your phone." });
    } catch (error) {
      setNote({ kind: "error", message: `Test notification failed: ${errorMessage(error)}` });
    } finally {
      setBusy(false);
    }
  }, []);

  const dirty =
    status !== null && (portField !== String(status.port) || topicField !== (status.ntfyTopic ?? ""));

  return (
    <SettingGroup id="settings-remote" label="Remote access">
      {status === null ? (
        <SettingNote role={loadError ? "alert" : "status"}>
          {loadError ?? "Loading remote status…"}
        </SettingNote>
      ) : (
        <>
          <SettingRow
            label="Phone remote"
            description="Drive Argmax from your phone over your Tailscale network. The bridge listens on this Mac only."
            control={
              <Toggle
                ariaLabel="Enable phone remote"
                checked={status.enabled}
                onChange={(next) =>
                  void saveConfig(next, {
                    port: String(status.port),
                    ntfyTopic: status.ntfyTopic ?? ""
                  })
                }
              />
            }
          />

          {status.enabled ? (
            <div className="settings-remote-pairing">
              <div
                className="settings-remote-qr"
                role="img"
                aria-label="Pairing QR code"
                // Trusted markup: SVG generated by our own Rust backend from
                // the pairing URL, never from remote input.
                dangerouslySetInnerHTML={{ __html: status.qrSvg }}
              />
              <div className="settings-remote-pairing-info">
                <p className="settings-note">
                  Scan with your phone's camera. The link carries the pairing token in the URL
                  fragment, so it never crosses the network.
                </p>
                <CopyValueRow label="Pairing link" value={status.pairingUrl} />
                <CopyValueRow label="Tailscale proxy" value={status.serveCommand} code />
                {status.tailnetUrl === null ? (
                  <p className="settings-note" data-tone="warn">
                    Tailscale CLI not found — the QR points at this Mac only. Install Tailscale to
                    reach it from your phone.
                  </p>
                ) : !status.tailscaleRunning ? (
                  <p className="settings-note" data-tone="warn">
                    Tailscale is not running, so the phone link will not connect until you start it.
                  </p>
                ) : null}
                {!status.serving ? (
                  <p className="settings-note" role="alert" data-tone="warn">
                    The bridge is enabled but not running. Try a different port.
                  </p>
                ) : null}
              </div>
            </div>
          ) : null}

          <SettingRow
            label="Port"
            htmlFor="settings-remote-port"
            control={
              <input
                id="settings-remote-port"
                className="settings-text-input settings-remote-port"
                inputMode="numeric"
                value={portField}
                onChange={(event) => setPortField(event.target.value)}
              />
            }
          />

          <SettingRow
            label="ntfy topic"
            description="Push when a session needs approval, blocks, fails, or finishes. Bare names use ntfy.sh, so pick something unguessable."
            htmlFor="settings-remote-ntfy"
            control={
              <input
                id="settings-remote-ntfy"
                className="settings-text-input"
                placeholder="argmax-yourname"
                value={topicField}
                onChange={(event) => setTopicField(event.target.value)}
              />
            }
          />

          <div className="settings-remote-actions">
            <button
              type="button"
              className="settings-button"
              disabled={busy || !dirty}
              onClick={() => void saveConfig(status.enabled)}
            >
              Save changes
            </button>
            <button
              type="button"
              className="settings-button"
              disabled={busy || status.ntfyTopic === null || dirty}
              title={
                status.ntfyTopic === null
                  ? "Save an ntfy topic first"
                  : dirty
                    ? "Save your changes first"
                    : undefined
              }
              onClick={() => void sendTestNotification()}
            >
              Send test notification
            </button>
            <button
              type="button"
              className="settings-button"
              aria-label="Refresh remote status"
              disabled={busy}
              onClick={() => void loadStatus()}
            >
              <RefreshCw size={13} aria-hidden="true" />
              <span>Refresh</span>
            </button>
          </div>
          {note ? (
            <p
              className="settings-note settings-form-status"
              data-status={note.kind}
              role={note.kind === "error" ? "alert" : "status"}
            >
              {note.message}
            </p>
          ) : null}
        </>
      )}
    </SettingGroup>
  );
}

function CopyValueRow({
  label,
  value,
  code = false
}: {
  label: string;
  value: string;
  code?: boolean;
}): JSX.Element {
  const [copyFlash, copy] = useCopyToClipboard();
  return (
    <div className="settings-remote-copyrow">
      <span className="settings-remote-copyrow-label">{label}</span>
      {code ? <code>{value}</code> : <span className="settings-remote-copyrow-value">{value}</span>}
      <button
        type="button"
        className="settings-button"
        onClick={() => void copy(value)}
        aria-label={`Copy ${label.toLowerCase()}`}
      >
        {copyFlash === "copied" ? <Check size={13} aria-hidden="true" /> : <Copy size={13} aria-hidden="true" />}
        <span>{copyFlash === "copied" ? "Copied" : copyFlash === "failed" ? "Couldn't copy" : "Copy"}</span>
      </button>
    </div>
  );
}
