// Generated by scripts/export-ios-agent-emblems.mjs. Do not edit by hand.
//
// The subagent emblem set: twelve shapes on a 16x16 grid, and the shape and
// session-icon hue each codename owns. Owned by
// src/renderer/lib/agentEmblems.ts — edit there and re-run
// `npm run export:ios-agent-emblems`.

import SwiftUI

enum AgentEmblemArt {
    static let shapes: [String] = [
        "trefoil",
        "hourglass",
        "orbit",
        "pinwheel",
        "cluster",
        "clover",
        "bloom",
        "wreath",
        "quad",
        "star",
        "gem",
        "shell"
    ]

    static let hues: [String] = [
        "green",
        "teal",
        "blue",
        "violet",
        "plum",
        "clay",
        "amber",
        "pink",
        "red"
    ]

    /// SCIENTIST_NAMES in order, because `fallbackCodename` indexes it.
    static let codenames: [String] = [
        "Turing",
        "Einstein",
        "Curie",
        "Newton",
        "Noether",
        "Lovelace",
        "Feynman",
        "Euler",
        "Gauss",
        "Hopper",
        "Shannon",
        "Dirac",
        "Bohr",
        "Maxwell",
        "Faraday",
        "Planck",
        "Ramanujan",
        "Hilbert",
        "Dijkstra",
        "Knuth",
        "Galileo",
        "Kepler",
        "Fermi",
        "Heisenberg",
        "Schrödinger",
        "Riemann",
        "Cantor",
        "Meitner",
        "Hamming",
        "Neumann",
        "Babbage",
        "Boole",
        "Gödel",
        "Church",
        "Kleene",
        "Lamport",
        "Liskov",
        "Hamilton",
        "Erdős",
        "Galois",
        "Abel",
        "Fourier",
        "Laplace",
        "Lagrange",
        "Bayes",
        "Fermat",
        "Pascal",
        "Leibniz",
        "Poincaré",
        "Kolmogorov",
        "Markov",
        "Pauli",
        "Rutherford",
        "Tesla",
        "Hertz",
        "Kelvin",
        "Joule",
        "Hubble",
        "Franklin",
        "Hypatia",
        "Archimedes",
        "Euclid",
        "Pythagoras",
        "Fibonacci",
        "Khwarizmi",
        "Descartes",
        "Bernoulli",
        "Cauchy",
        "Banach",
        "Conway",
        "Germain",
        "Kovalevskaya",
        "Mirzakhani",
        "Mandelbrot",
        "Boltzmann",
        "Lorentz",
        "Hawking",
        "Copernicus",
        "Ampère",
        "Ohm",
        "Ångström",
        "Bose",
        "Chandrasekhar",
        "Wu",
        "Rubin",
        "Landau",
        "Higgs",
        "McCarthy",
        "Backus",
        "Ritchie",
        "Thompson",
        "Zuse",
        "Wirth",
        "Hoare",
        "Karp",
        "Engelbart",
        "Cerf",
        "Rivest",
        "Codd",
        "Huffman"
    ]

    /// Codename → (shape, hue).
    static let byCodename: [String: (shape: String, hue: String)] = [
        "Turing": (shape: "cluster", hue: "green"),
        "Einstein": (shape: "star", hue: "violet"),
        "Curie": (shape: "orbit", hue: "pink"),
        "Newton": (shape: "wreath", hue: "teal"),
        "Noether": (shape: "trefoil", hue: "clay"),
        "Lovelace": (shape: "clover", hue: "red"),
        "Feynman": (shape: "gem", hue: "blue"),
        "Euler": (shape: "pinwheel", hue: "amber"),
        "Gauss": (shape: "quad", hue: "green"),
        "Hopper": (shape: "hourglass", hue: "plum"),
        "Shannon": (shape: "bloom", hue: "pink"),
        "Dirac": (shape: "shell", hue: "teal"),
        "Bohr": (shape: "cluster", hue: "clay"),
        "Maxwell": (shape: "star", hue: "red"),
        "Faraday": (shape: "orbit", hue: "violet"),
        "Planck": (shape: "wreath", hue: "amber"),
        "Ramanujan": (shape: "trefoil", hue: "teal"),
        "Hilbert": (shape: "clover", hue: "plum"),
        "Dijkstra": (shape: "gem", hue: "pink"),
        "Knuth": (shape: "pinwheel", hue: "blue"),
        "Galileo": (shape: "quad", hue: "clay"),
        "Kepler": (shape: "hourglass", hue: "green"),
        "Fermi": (shape: "bloom", hue: "violet"),
        "Heisenberg": (shape: "shell", hue: "amber"),
        "Schrödinger": (shape: "cluster", hue: "teal"),
        "Riemann": (shape: "star", hue: "plum"),
        "Cantor": (shape: "orbit", hue: "red"),
        "Meitner": (shape: "wreath", hue: "blue"),
        "Hamming": (shape: "trefoil", hue: "amber"),
        "Neumann": (shape: "clover", hue: "green"),
        "Babbage": (shape: "gem", hue: "violet"),
        "Boole": (shape: "pinwheel", hue: "pink"),
        "Gödel": (shape: "quad", hue: "teal"),
        "Church": (shape: "hourglass", hue: "clay"),
        "Kleene": (shape: "bloom", hue: "red"),
        "Lamport": (shape: "shell", hue: "blue"),
        "Liskov": (shape: "cluster", hue: "amber"),
        "Hamilton": (shape: "star", hue: "green"),
        "Erdős": (shape: "orbit", hue: "plum"),
        "Galois": (shape: "wreath", hue: "pink"),
        "Abel": (shape: "trefoil", hue: "blue"),
        "Fourier": (shape: "clover", hue: "clay"),
        "Laplace": (shape: "gem", hue: "red"),
        "Lagrange": (shape: "pinwheel", hue: "violet"),
        "Bayes": (shape: "quad", hue: "amber"),
        "Fermat": (shape: "hourglass", hue: "teal"),
        "Pascal": (shape: "bloom", hue: "plum"),
        "Leibniz": (shape: "shell", hue: "pink"),
        "Poincaré": (shape: "cluster", hue: "blue"),
        "Kolmogorov": (shape: "star", hue: "clay"),
        "Markov": (shape: "orbit", hue: "green"),
        "Pauli": (shape: "wreath", hue: "violet"),
        "Rutherford": (shape: "trefoil", hue: "pink"),
        "Tesla": (shape: "clover", hue: "teal"),
        "Hertz": (shape: "gem", hue: "plum"),
        "Kelvin": (shape: "pinwheel", hue: "red"),
        "Joule": (shape: "quad", hue: "blue"),
        "Hubble": (shape: "hourglass", hue: "amber"),
        "Franklin": (shape: "bloom", hue: "green"),
        "Hypatia": (shape: "shell", hue: "violet"),
        "Archimedes": (shape: "cluster", hue: "pink"),
        "Euclid": (shape: "star", hue: "teal"),
        "Pythagoras": (shape: "orbit", hue: "clay"),
        "Fibonacci": (shape: "wreath", hue: "red"),
        "Khwarizmi": (shape: "trefoil", hue: "violet"),
        "Descartes": (shape: "clover", hue: "amber"),
        "Bernoulli": (shape: "gem", hue: "green"),
        "Cauchy": (shape: "pinwheel", hue: "plum"),
        "Banach": (shape: "quad", hue: "pink"),
        "Conway": (shape: "hourglass", hue: "blue"),
        "Germain": (shape: "bloom", hue: "clay"),
        "Kovalevskaya": (shape: "shell", hue: "red"),
        "Mirzakhani": (shape: "cluster", hue: "violet"),
        "Mandelbrot": (shape: "star", hue: "amber"),
        "Boltzmann": (shape: "orbit", hue: "teal"),
        "Lorentz": (shape: "wreath", hue: "plum"),
        "Hawking": (shape: "trefoil", hue: "red"),
        "Copernicus": (shape: "clover", hue: "blue"),
        "Ampère": (shape: "gem", hue: "clay"),
        "Ohm": (shape: "pinwheel", hue: "green"),
        "Ångström": (shape: "quad", hue: "violet"),
        "Bose": (shape: "hourglass", hue: "pink"),
        "Chandrasekhar": (shape: "bloom", hue: "teal"),
        "Wu": (shape: "shell", hue: "plum"),
        "Rubin": (shape: "cluster", hue: "red"),
        "Landau": (shape: "star", hue: "blue"),
        "Higgs": (shape: "orbit", hue: "amber"),
        "McCarthy": (shape: "wreath", hue: "green"),
        "Backus": (shape: "trefoil", hue: "plum"),
        "Ritchie": (shape: "clover", hue: "pink"),
        "Thompson": (shape: "gem", hue: "teal"),
        "Zuse": (shape: "pinwheel", hue: "clay"),
        "Wirth": (shape: "quad", hue: "red"),
        "Hoare": (shape: "hourglass", hue: "violet"),
        "Karp": (shape: "bloom", hue: "amber"),
        "Engelbart": (shape: "shell", hue: "green"),
        "Cerf": (shape: "cluster", hue: "plum"),
        "Rivest": (shape: "star", hue: "pink"),
        "Codd": (shape: "orbit", hue: "blue"),
        "Huffman": (shape: "wreath", hue: "clay")
    ]

    /// The shapes that carry a hole — the orbit's ring, the bloom's open
    /// centre, the gem's facets — and so have to be filled even-odd. The rest
    /// are unions of subpaths wound the same way.
    static let evenOddShapes: Set<String> = [
        "orbit",
        "bloom",
        "gem"
    ]

    /// The shape's outline on the 16x16 grid. Built once: an emblem is drawn
    /// three times over in every row, and a list of them scrolls.
    static func path(_ shape: String) -> Path { paths[shape] ?? paths["quad"]! }

    private static let paths: [String: Path] = Dictionary(
        uniqueKeysWithValues: shapes.map { ($0, makePath($0)) }
    )

    private static func makePath(_ shape: String) -> Path {
        var path = Path()
        switch shape {
        case "trefoil":
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 8, y: 1.1), control1: CGPoint(x: 3.54, y: 6.89), control2: CGPoint(x: 4.03, y: 2.11))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 11.97, y: 2.11), control2: CGPoint(x: 12.46, y: 6.89))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 13.98, y: 11.45), control1: CGPoint(x: 11.2, y: 4.69), control2: CGPoint(x: 15.08, y: 7.5))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 11.11, y: 14.38), control2: CGPoint(x: 6.73, y: 12.42))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 2.02, y: 11.45), control1: CGPoint(x: 9.27, y: 12.42), control2: CGPoint(x: 4.89, y: 14.38))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 0.92, y: 7.5), control2: CGPoint(x: 4.8, y: 4.69))
            path.closeSubpath()
        case "hourglass":
            path.move(to: CGPoint(x: 8, y: 8.75))
            path.addLine(to: CGPoint(x: 2.28, y: 4.14))
            path.addCurve(to: CGPoint(x: 8, y: 1.099), control1: CGPoint(x: 3.563, y: 2.239), control2: CGPoint(x: 5.706, y: 1.099))
            path.addCurve(to: CGPoint(x: 13.72, y: 4.14), control1: CGPoint(x: 10.294, y: 1.099), control2: CGPoint(x: 12.437, y: 2.239))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 7.25))
            path.addLine(to: CGPoint(x: 13.72, y: 11.86))
            path.addCurve(to: CGPoint(x: 8, y: 14.901), control1: CGPoint(x: 12.437, y: 13.761), control2: CGPoint(x: 10.294, y: 14.901))
            path.addCurve(to: CGPoint(x: 2.28, y: 11.86), control1: CGPoint(x: 5.706, y: 14.901), control2: CGPoint(x: 3.563, y: 13.761))
            path.closeSubpath()
        case "orbit":
            path.move(to: CGPoint(x: 1.1, y: 8))
            path.addCurve(to: CGPoint(x: 8, y: 14.9), control1: CGPoint(x: 1.1, y: 11.811), control2: CGPoint(x: 4.189, y: 14.9))
            path.addCurve(to: CGPoint(x: 14.9, y: 8), control1: CGPoint(x: 11.811, y: 14.9), control2: CGPoint(x: 14.9, y: 11.811))
            path.addCurve(to: CGPoint(x: 8, y: 1.1), control1: CGPoint(x: 14.9, y: 4.189), control2: CGPoint(x: 11.811, y: 1.1))
            path.addCurve(to: CGPoint(x: 1.1, y: 8), control1: CGPoint(x: 4.189, y: 1.1), control2: CGPoint(x: 1.1, y: 4.189))
            path.closeSubpath()
            path.move(to: CGPoint(x: 2.3, y: 8))
            path.addCurve(to: CGPoint(x: 5.15, y: 12.936), control1: CGPoint(x: 2.3, y: 10.036), control2: CGPoint(x: 3.386, y: 11.918))
            path.addCurve(to: CGPoint(x: 10.85, y: 12.936), control1: CGPoint(x: 6.914, y: 13.955), control2: CGPoint(x: 9.086, y: 13.955))
            path.addCurve(to: CGPoint(x: 13.7, y: 8), control1: CGPoint(x: 12.614, y: 11.918), control2: CGPoint(x: 13.7, y: 10.036))
            path.addCurve(to: CGPoint(x: 10.85, y: 3.064), control1: CGPoint(x: 13.7, y: 5.964), control2: CGPoint(x: 12.614, y: 4.082))
            path.addCurve(to: CGPoint(x: 5.15, y: 3.064), control1: CGPoint(x: 9.086, y: 2.045), control2: CGPoint(x: 6.914, y: 2.045))
            path.addCurve(to: CGPoint(x: 2.3, y: 8), control1: CGPoint(x: 3.386, y: 4.082), control2: CGPoint(x: 2.3, y: 5.964))
            path.closeSubpath()
            path.move(to: CGPoint(x: 5.6, y: 5.1))
            path.addCurve(to: CGPoint(x: 8, y: 7.5), control1: CGPoint(x: 5.6, y: 6.425), control2: CGPoint(x: 6.675, y: 7.5))
            path.addCurve(to: CGPoint(x: 10.4, y: 5.1), control1: CGPoint(x: 9.325, y: 7.5), control2: CGPoint(x: 10.4, y: 6.425))
            path.addCurve(to: CGPoint(x: 8, y: 2.7), control1: CGPoint(x: 10.4, y: 3.775), control2: CGPoint(x: 9.325, y: 2.7))
            path.addCurve(to: CGPoint(x: 5.6, y: 5.1), control1: CGPoint(x: 6.675, y: 2.7), control2: CGPoint(x: 5.6, y: 3.775))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8.11, y: 9.45))
            path.addCurve(to: CGPoint(x: 10.51, y: 11.85), control1: CGPoint(x: 8.11, y: 10.775), control2: CGPoint(x: 9.185, y: 11.85))
            path.addCurve(to: CGPoint(x: 12.91, y: 9.45), control1: CGPoint(x: 11.835, y: 11.85), control2: CGPoint(x: 12.91, y: 10.775))
            path.addCurve(to: CGPoint(x: 10.51, y: 7.05), control1: CGPoint(x: 12.91, y: 8.125), control2: CGPoint(x: 11.835, y: 7.05))
            path.addCurve(to: CGPoint(x: 8.11, y: 9.45), control1: CGPoint(x: 9.185, y: 7.05), control2: CGPoint(x: 8.11, y: 8.125))
            path.closeSubpath()
            path.move(to: CGPoint(x: 3.09, y: 9.45))
            path.addCurve(to: CGPoint(x: 5.49, y: 11.85), control1: CGPoint(x: 3.09, y: 10.775), control2: CGPoint(x: 4.165, y: 11.85))
            path.addCurve(to: CGPoint(x: 7.89, y: 9.45), control1: CGPoint(x: 6.815, y: 11.85), control2: CGPoint(x: 7.89, y: 10.775))
            path.addCurve(to: CGPoint(x: 5.49, y: 7.05), control1: CGPoint(x: 7.89, y: 8.125), control2: CGPoint(x: 6.815, y: 7.05))
            path.addCurve(to: CGPoint(x: 3.09, y: 9.45), control1: CGPoint(x: 4.165, y: 7.05), control2: CGPoint(x: 3.09, y: 8.125))
            path.closeSubpath()
        case "pinwheel":
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 8, y: 1.1), control1: CGPoint(x: 6.68, y: 5.3), control2: CGPoint(x: 6.67, y: 2.25))
            path.addCurve(to: CGPoint(x: 13.85, y: 4.34), control1: CGPoint(x: 10.378, y: 1.1), control2: CGPoint(x: 12.589, y: 2.324))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 11.52, y: 4.6), control2: CGPoint(x: 9.01, y: 6.39))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 14.9, y: 8), control1: CGPoint(x: 10.7, y: 6.68), control2: CGPoint(x: 13.75, y: 6.67))
            path.addCurve(to: CGPoint(x: 11.66, y: 13.85), control1: CGPoint(x: 14.9, y: 10.378), control2: CGPoint(x: 13.676, y: 12.589))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 11.4, y: 11.52), control2: CGPoint(x: 9.61, y: 9.01))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 8, y: 14.9), control1: CGPoint(x: 9.32, y: 10.7), control2: CGPoint(x: 9.33, y: 13.75))
            path.addCurve(to: CGPoint(x: 2.15, y: 11.66), control1: CGPoint(x: 5.622, y: 14.9), control2: CGPoint(x: 3.411, y: 13.676))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 4.48, y: 11.4), control2: CGPoint(x: 6.99, y: 9.61))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 1.1, y: 8), control1: CGPoint(x: 5.3, y: 9.32), control2: CGPoint(x: 2.25, y: 9.33))
            path.addCurve(to: CGPoint(x: 4.34, y: 2.15), control1: CGPoint(x: 1.1, y: 5.622), control2: CGPoint(x: 2.324, y: 3.411))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 4.6, y: 4.48), control2: CGPoint(x: 6.39, y: 6.99))
            path.closeSubpath()
        case "cluster":
            path.move(to: CGPoint(x: 8, y: 5.15))
            path.addLine(to: CGPoint(x: 10.85, y: 8))
            path.addLine(to: CGPoint(x: 8, y: 10.85))
            path.addLine(to: CGPoint(x: 5.15, y: 8))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 1.1))
            path.addLine(to: CGPoint(x: 11.3, y: 3.8))
            path.addLine(to: CGPoint(x: 8, y: 6.5))
            path.addLine(to: CGPoint(x: 4.7, y: 3.8))
            path.closeSubpath()
            path.move(to: CGPoint(x: 14.9, y: 8))
            path.addLine(to: CGPoint(x: 12.2, y: 11.3))
            path.addLine(to: CGPoint(x: 9.5, y: 8))
            path.addLine(to: CGPoint(x: 12.2, y: 4.7))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 14.9))
            path.addLine(to: CGPoint(x: 4.7, y: 12.2))
            path.addLine(to: CGPoint(x: 8, y: 9.5))
            path.addLine(to: CGPoint(x: 11.3, y: 12.2))
            path.closeSubpath()
            path.move(to: CGPoint(x: 1.1, y: 8))
            path.addLine(to: CGPoint(x: 3.8, y: 4.7))
            path.addLine(to: CGPoint(x: 6.5, y: 8))
            path.addLine(to: CGPoint(x: 3.8, y: 11.3))
            path.closeSubpath()
        case "clover":
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 5.13, y: 1.84), control1: CGPoint(x: 6.33, y: 6.27), control2: CGPoint(x: 4.32, y: 3.91))
            path.addCurve(to: CGPoint(x: 8, y: 2.65), control1: CGPoint(x: 6.52, y: 1.57), control2: CGPoint(x: 7.38, y: 2.13))
            path.addCurve(to: CGPoint(x: 10.87, y: 1.84), control1: CGPoint(x: 8.62, y: 2.13), control2: CGPoint(x: 9.48, y: 1.57))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 11.68, y: 3.91), control2: CGPoint(x: 9.67, y: 6.27))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 14.16, y: 5.13), control1: CGPoint(x: 9.73, y: 6.33), control2: CGPoint(x: 12.09, y: 4.32))
            path.addCurve(to: CGPoint(x: 13.35, y: 8), control1: CGPoint(x: 14.43, y: 6.52), control2: CGPoint(x: 13.87, y: 7.38))
            path.addCurve(to: CGPoint(x: 14.16, y: 10.87), control1: CGPoint(x: 13.87, y: 8.62), control2: CGPoint(x: 14.43, y: 9.48))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 12.09, y: 11.68), control2: CGPoint(x: 9.73, y: 9.67))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 10.87, y: 14.16), control1: CGPoint(x: 9.67, y: 9.73), control2: CGPoint(x: 11.68, y: 12.09))
            path.addCurve(to: CGPoint(x: 8, y: 13.35), control1: CGPoint(x: 9.48, y: 14.43), control2: CGPoint(x: 8.62, y: 13.87))
            path.addCurve(to: CGPoint(x: 5.13, y: 14.16), control1: CGPoint(x: 7.38, y: 13.87), control2: CGPoint(x: 6.52, y: 14.43))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 4.32, y: 12.09), control2: CGPoint(x: 6.33, y: 9.73))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 8))
            path.addCurve(to: CGPoint(x: 1.84, y: 10.87), control1: CGPoint(x: 6.27, y: 9.67), control2: CGPoint(x: 3.91, y: 11.68))
            path.addCurve(to: CGPoint(x: 2.65, y: 8), control1: CGPoint(x: 1.57, y: 9.48), control2: CGPoint(x: 2.13, y: 8.62))
            path.addCurve(to: CGPoint(x: 1.84, y: 5.13), control1: CGPoint(x: 2.13, y: 7.38), control2: CGPoint(x: 1.57, y: 6.52))
            path.addCurve(to: CGPoint(x: 8, y: 8), control1: CGPoint(x: 3.91, y: 4.32), control2: CGPoint(x: 6.27, y: 6.33))
            path.closeSubpath()
        case "bloom":
            path.move(to: CGPoint(x: 8, y: 1.1))
            path.addCurve(to: CGPoint(x: 10.33, y: 5.67), control1: CGPoint(x: 9.44, y: 1.76), control2: CGPoint(x: 11.13, y: 3))
            path.addCurve(to: CGPoint(x: 14.9, y: 8), control1: CGPoint(x: 13, y: 4.87), control2: CGPoint(x: 14.24, y: 6.56))
            path.addCurve(to: CGPoint(x: 10.33, y: 10.33), control1: CGPoint(x: 14.24, y: 9.44), control2: CGPoint(x: 13, y: 11.13))
            path.addCurve(to: CGPoint(x: 8, y: 14.9), control1: CGPoint(x: 11.13, y: 13), control2: CGPoint(x: 9.44, y: 14.24))
            path.addCurve(to: CGPoint(x: 5.67, y: 10.33), control1: CGPoint(x: 6.56, y: 14.24), control2: CGPoint(x: 4.87, y: 13))
            path.addCurve(to: CGPoint(x: 1.1, y: 8), control1: CGPoint(x: 3, y: 11.13), control2: CGPoint(x: 1.76, y: 9.44))
            path.addCurve(to: CGPoint(x: 5.67, y: 5.67), control1: CGPoint(x: 1.76, y: 6.56), control2: CGPoint(x: 3, y: 4.87))
            path.addCurve(to: CGPoint(x: 8, y: 1.1), control1: CGPoint(x: 4.87, y: 3), control2: CGPoint(x: 6.56, y: 1.76))
            path.closeSubpath()
            path.move(to: CGPoint(x: 6.1, y: 8))
            path.addCurve(to: CGPoint(x: 8, y: 9.9), control1: CGPoint(x: 6.1, y: 9.049), control2: CGPoint(x: 6.951, y: 9.9))
            path.addCurve(to: CGPoint(x: 9.9, y: 8), control1: CGPoint(x: 9.049, y: 9.9), control2: CGPoint(x: 9.9, y: 9.049))
            path.addCurve(to: CGPoint(x: 8, y: 6.1), control1: CGPoint(x: 9.9, y: 6.951), control2: CGPoint(x: 9.049, y: 6.1))
            path.addCurve(to: CGPoint(x: 6.1, y: 8), control1: CGPoint(x: 6.951, y: 6.1), control2: CGPoint(x: 6.1, y: 6.951))
            path.closeSubpath()
        case "wreath":
            path.move(to: CGPoint(x: 8, y: 5.66))
            path.addCurve(to: CGPoint(x: 10, y: 3.38), control1: CGPoint(x: 9.105, y: 5.66), control2: CGPoint(x: 10, y: 4.639))
            path.addCurve(to: CGPoint(x: 8, y: 1.1), control1: CGPoint(x: 10, y: 2.121), control2: CGPoint(x: 9.105, y: 1.1))
            path.addCurve(to: CGPoint(x: 6, y: 3.38), control1: CGPoint(x: 6.895, y: 1.1), control2: CGPoint(x: 6, y: 2.121))
            path.addCurve(to: CGPoint(x: 8, y: 5.66), control1: CGPoint(x: 6, y: 4.639), control2: CGPoint(x: 6.895, y: 5.66))
            path.closeSubpath()
            path.move(to: CGPoint(x: 10.03, y: 6.83))
            path.addCurve(to: CGPoint(x: 13.005, y: 7.422), control1: CGPoint(x: 10.582, y: 7.787), control2: CGPoint(x: 11.914, y: 8.052))
            path.addCurve(to: CGPoint(x: 13.98, y: 4.55), control1: CGPoint(x: 14.096, y: 6.793), control2: CGPoint(x: 14.532, y: 5.507))
            path.addCurve(to: CGPoint(x: 11.005, y: 3.958), control1: CGPoint(x: 13.428, y: 3.593), control2: CGPoint(x: 12.096, y: 3.328))
            path.addCurve(to: CGPoint(x: 10.03, y: 6.83), control1: CGPoint(x: 9.914, y: 4.587), control2: CGPoint(x: 9.478, y: 5.873))
            path.closeSubpath()
            path.move(to: CGPoint(x: 10.03, y: 9.17))
            path.addCurve(to: CGPoint(x: 11.005, y: 12.042), control1: CGPoint(x: 9.478, y: 10.127), control2: CGPoint(x: 9.914, y: 11.413))
            path.addCurve(to: CGPoint(x: 13.98, y: 11.45), control1: CGPoint(x: 12.096, y: 12.672), control2: CGPoint(x: 13.428, y: 12.407))
            path.addCurve(to: CGPoint(x: 13.005, y: 8.578), control1: CGPoint(x: 14.532, y: 10.493), control2: CGPoint(x: 14.096, y: 9.207))
            path.addCurve(to: CGPoint(x: 10.03, y: 9.17), control1: CGPoint(x: 11.914, y: 7.948), control2: CGPoint(x: 10.582, y: 8.213))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 10.34))
            path.addCurve(to: CGPoint(x: 6, y: 12.62), control1: CGPoint(x: 6.895, y: 10.34), control2: CGPoint(x: 6, y: 11.361))
            path.addCurve(to: CGPoint(x: 8, y: 14.9), control1: CGPoint(x: 6, y: 13.879), control2: CGPoint(x: 6.895, y: 14.9))
            path.addCurve(to: CGPoint(x: 10, y: 12.62), control1: CGPoint(x: 9.105, y: 14.9), control2: CGPoint(x: 10, y: 13.879))
            path.addCurve(to: CGPoint(x: 8, y: 10.34), control1: CGPoint(x: 10, y: 11.361), control2: CGPoint(x: 9.105, y: 10.34))
            path.closeSubpath()
            path.move(to: CGPoint(x: 5.97, y: 9.17))
            path.addCurve(to: CGPoint(x: 4.117, y: 8.24), control1: CGPoint(x: 5.613, y: 8.551), control2: CGPoint(x: 4.906, y: 8.196))
            path.addCurve(to: CGPoint(x: 2.142, y: 9.38), control1: CGPoint(x: 3.327, y: 8.283), control2: CGPoint(x: 2.574, y: 8.717))
            path.addCurve(to: CGPoint(x: 2.02, y: 11.45), control1: CGPoint(x: 1.709, y: 10.042), control2: CGPoint(x: 1.663, y: 10.831))
            path.addCurve(to: CGPoint(x: 3.873, y: 12.38), control1: CGPoint(x: 2.377, y: 12.069), control2: CGPoint(x: 3.084, y: 12.424))
            path.addCurve(to: CGPoint(x: 5.848, y: 11.24), control1: CGPoint(x: 4.663, y: 12.337), control2: CGPoint(x: 5.416, y: 11.903))
            path.addCurve(to: CGPoint(x: 5.97, y: 9.17), control1: CGPoint(x: 6.281, y: 10.578), control2: CGPoint(x: 6.327, y: 9.789))
            path.closeSubpath()
            path.move(to: CGPoint(x: 5.97, y: 6.83))
            path.addCurve(to: CGPoint(x: 5.848, y: 4.76), control1: CGPoint(x: 6.327, y: 6.211), control2: CGPoint(x: 6.281, y: 5.422))
            path.addCurve(to: CGPoint(x: 3.873, y: 3.62), control1: CGPoint(x: 5.416, y: 4.097), control2: CGPoint(x: 4.663, y: 3.663))
            path.addCurve(to: CGPoint(x: 2.02, y: 4.55), control1: CGPoint(x: 3.084, y: 3.576), control2: CGPoint(x: 2.377, y: 3.931))
            path.addCurve(to: CGPoint(x: 2.142, y: 6.62), control1: CGPoint(x: 1.663, y: 5.169), control2: CGPoint(x: 1.709, y: 5.958))
            path.addCurve(to: CGPoint(x: 4.117, y: 7.76), control1: CGPoint(x: 2.574, y: 7.283), control2: CGPoint(x: 3.327, y: 7.717))
            path.addCurve(to: CGPoint(x: 5.97, y: 6.83), control1: CGPoint(x: 4.906, y: 7.804), control2: CGPoint(x: 5.613, y: 7.449))
            path.closeSubpath()
        case "quad":
            path.move(to: CGPoint(x: 8, y: 5.1))
            path.addCurve(to: CGPoint(x: 10.9, y: 8), control1: CGPoint(x: 8, y: 6.702), control2: CGPoint(x: 9.298, y: 8))
            path.addCurve(to: CGPoint(x: 13.8, y: 5.1), control1: CGPoint(x: 12.502, y: 8), control2: CGPoint(x: 13.8, y: 6.702))
            path.addCurve(to: CGPoint(x: 10.9, y: 2.2), control1: CGPoint(x: 13.8, y: 3.498), control2: CGPoint(x: 12.502, y: 2.2))
            path.addCurve(to: CGPoint(x: 8, y: 5.1), control1: CGPoint(x: 9.298, y: 2.2), control2: CGPoint(x: 8, y: 3.498))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8, y: 10.9))
            path.addCurve(to: CGPoint(x: 10.9, y: 13.8), control1: CGPoint(x: 8, y: 12.502), control2: CGPoint(x: 9.298, y: 13.8))
            path.addCurve(to: CGPoint(x: 13.8, y: 10.9), control1: CGPoint(x: 12.502, y: 13.8), control2: CGPoint(x: 13.8, y: 12.502))
            path.addCurve(to: CGPoint(x: 10.9, y: 8), control1: CGPoint(x: 13.8, y: 9.298), control2: CGPoint(x: 12.502, y: 8))
            path.addCurve(to: CGPoint(x: 8, y: 10.9), control1: CGPoint(x: 9.298, y: 8), control2: CGPoint(x: 8, y: 9.298))
            path.closeSubpath()
            path.move(to: CGPoint(x: 2.2, y: 10.9))
            path.addCurve(to: CGPoint(x: 5.1, y: 13.8), control1: CGPoint(x: 2.2, y: 12.502), control2: CGPoint(x: 3.498, y: 13.8))
            path.addCurve(to: CGPoint(x: 8, y: 10.9), control1: CGPoint(x: 6.702, y: 13.8), control2: CGPoint(x: 8, y: 12.502))
            path.addCurve(to: CGPoint(x: 5.1, y: 8), control1: CGPoint(x: 8, y: 9.298), control2: CGPoint(x: 6.702, y: 8))
            path.addCurve(to: CGPoint(x: 2.2, y: 10.9), control1: CGPoint(x: 3.498, y: 8), control2: CGPoint(x: 2.2, y: 9.298))
            path.closeSubpath()
            path.move(to: CGPoint(x: 2.2, y: 5.1))
            path.addCurve(to: CGPoint(x: 5.1, y: 8), control1: CGPoint(x: 2.2, y: 6.702), control2: CGPoint(x: 3.498, y: 8))
            path.addCurve(to: CGPoint(x: 8, y: 5.1), control1: CGPoint(x: 6.702, y: 8), control2: CGPoint(x: 8, y: 6.702))
            path.addCurve(to: CGPoint(x: 5.1, y: 2.2), control1: CGPoint(x: 8, y: 3.498), control2: CGPoint(x: 6.702, y: 2.2))
            path.addCurve(to: CGPoint(x: 2.2, y: 5.1), control1: CGPoint(x: 3.498, y: 2.2), control2: CGPoint(x: 2.2, y: 3.498))
            path.closeSubpath()
        case "star":
            path.move(to: CGPoint(x: 8, y: 1.1))
            path.addLine(to: CGPoint(x: 9.63, y: 4.07))
            path.addLine(to: CGPoint(x: 12.88, y: 3.12))
            path.addLine(to: CGPoint(x: 11.93, y: 6.37))
            path.addLine(to: CGPoint(x: 14.9, y: 8))
            path.addLine(to: CGPoint(x: 11.93, y: 9.63))
            path.addLine(to: CGPoint(x: 12.88, y: 12.88))
            path.addLine(to: CGPoint(x: 9.63, y: 11.93))
            path.addLine(to: CGPoint(x: 8, y: 14.9))
            path.addLine(to: CGPoint(x: 6.37, y: 11.93))
            path.addLine(to: CGPoint(x: 3.12, y: 12.88))
            path.addLine(to: CGPoint(x: 4.07, y: 9.63))
            path.addLine(to: CGPoint(x: 1.1, y: 8))
            path.addLine(to: CGPoint(x: 4.07, y: 6.37))
            path.addLine(to: CGPoint(x: 3.12, y: 3.12))
            path.addLine(to: CGPoint(x: 6.37, y: 4.07))
            path.closeSubpath()
        case "gem":
            path.move(to: CGPoint(x: 8, y: 1.1))
            path.addLine(to: CGPoint(x: 13.98, y: 4.55))
            path.addLine(to: CGPoint(x: 13.98, y: 11.45))
            path.addLine(to: CGPoint(x: 8, y: 14.9))
            path.addLine(to: CGPoint(x: 2.02, y: 11.45))
            path.addLine(to: CGPoint(x: 2.02, y: 4.55))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8.6, y: 6.5))
            path.addLine(to: CGPoint(x: 8.85, y: 1.9))
            path.addLine(to: CGPoint(x: 7.15, y: 1.9))
            path.addLine(to: CGPoint(x: 7.41, y: 6.5))
            path.closeSubpath()
            path.move(to: CGPoint(x: 9, y: 9.27))
            path.addLine(to: CGPoint(x: 12.86, y: 11.79))
            path.addLine(to: CGPoint(x: 13.71, y: 10.31))
            path.addLine(to: CGPoint(x: 9.6, y: 8.23))
            path.closeSubpath()
            path.move(to: CGPoint(x: 6.4, y: 8.23))
            path.addLine(to: CGPoint(x: 2.29, y: 10.31))
            path.addLine(to: CGPoint(x: 3.14, y: 11.79))
            path.addLine(to: CGPoint(x: 7, y: 9.27))
            path.closeSubpath()
        case "shell":
            path.move(to: CGPoint(x: 4.95, y: 4.7))
            path.addCurve(to: CGPoint(x: 6.475, y: 7.341), control1: CGPoint(x: 4.95, y: 5.79), control2: CGPoint(x: 5.531, y: 6.797))
            path.addCurve(to: CGPoint(x: 9.525, y: 7.341), control1: CGPoint(x: 7.419, y: 7.886), control2: CGPoint(x: 8.581, y: 7.886))
            path.addCurve(to: CGPoint(x: 11.05, y: 4.7), control1: CGPoint(x: 10.469, y: 6.797), control2: CGPoint(x: 11.05, y: 5.79))
            path.addCurve(to: CGPoint(x: 9.525, y: 2.059), control1: CGPoint(x: 11.05, y: 3.61), control2: CGPoint(x: 10.469, y: 2.603))
            path.addCurve(to: CGPoint(x: 6.475, y: 2.059), control1: CGPoint(x: 8.581, y: 1.514), control2: CGPoint(x: 7.419, y: 1.514))
            path.addCurve(to: CGPoint(x: 4.95, y: 4.7), control1: CGPoint(x: 5.531, y: 2.603), control2: CGPoint(x: 4.95, y: 3.61))
            path.closeSubpath()
            path.move(to: CGPoint(x: 7.07, y: 6.01))
            path.addCurve(to: CGPoint(x: 13.38, y: 9.54), control1: CGPoint(x: 9.77, y: 6.23), control2: CGPoint(x: 12.4, y: 8.15))
            path.addCurve(to: CGPoint(x: 5.8, y: 3.07), control1: CGPoint(x: 14.8, y: 6.8), control2: CGPoint(x: 11.86, y: 2.28))
            path.closeSubpath()
            path.move(to: CGPoint(x: 4.95, y: 11.3))
            path.addCurve(to: CGPoint(x: 6.475, y: 13.941), control1: CGPoint(x: 4.95, y: 12.39), control2: CGPoint(x: 5.531, y: 13.397))
            path.addCurve(to: CGPoint(x: 9.525, y: 13.941), control1: CGPoint(x: 7.419, y: 14.486), control2: CGPoint(x: 8.581, y: 14.486))
            path.addCurve(to: CGPoint(x: 11.05, y: 11.3), control1: CGPoint(x: 10.469, y: 13.397), control2: CGPoint(x: 11.05, y: 12.39))
            path.addCurve(to: CGPoint(x: 9.525, y: 8.659), control1: CGPoint(x: 11.05, y: 10.21), control2: CGPoint(x: 10.469, y: 9.203))
            path.addCurve(to: CGPoint(x: 6.475, y: 8.659), control1: CGPoint(x: 8.581, y: 8.114), control2: CGPoint(x: 7.419, y: 8.114))
            path.addCurve(to: CGPoint(x: 4.95, y: 11.3), control1: CGPoint(x: 5.531, y: 9.203), control2: CGPoint(x: 4.95, y: 10.21))
            path.closeSubpath()
            path.move(to: CGPoint(x: 8.93, y: 9.99))
            path.addCurve(to: CGPoint(x: 2.62, y: 6.46), control1: CGPoint(x: 6.23, y: 9.77), control2: CGPoint(x: 3.6, y: 7.85))
            path.addCurve(to: CGPoint(x: 10.2, y: 12.93), control1: CGPoint(x: 1.2, y: 9.2), control2: CGPoint(x: 4.14, y: 13.72))
            path.closeSubpath()
        default:
            break
        }
        return path
    }
}
