import SwiftUI
import UIKit

// The type scale, as one modifier per role — and the one place that knows
// which typeface the app is drawing in.
//
// Every role is built from a *text style*, so Dynamic Type moves the whole app
// and nothing is pinned to a point size. Semibold for screen titles; row titles
// and everything else regular — and mono wherever the text is an identifier a
// person might have to type back: branch names, model ids, the pairing link.
//
// Reaching for `.font(...)` directly is what this exists to prevent: a system
// font named at a call site is a surface the font setting cannot reach, so
// `npm run check:ios-fonts` fails the build on one.

/// Which typeface the app draws in.
///
/// The ids are the desktop's own (`src/renderer/lib/fonts.ts`) where there is
/// a matching choice. `system` and `sfRounded` are phone-native choices.
enum AppTypeface: String, CaseIterable, Identifiable, Sendable {
    /// SF Pro, and SF Mono for identifiers: what iOS itself is set in and the
    /// closest match to the ChatGPT iPhone screenshots.
    case system
    /// Apple's rounded system variant for a softer interface voice.
    case sfRounded = "sf-rounded"
    /// Geist for prose. Identifiers stay in the system's SF Mono.
    case geist = "geist-sans"
    /// Inter, a widely used screen-oriented UI sans.
    case inter

    var id: String { rawValue }

    var label: String {
        switch self {
        case .system: return "SF Pro"
        case .sfRounded: return "SF Rounded"
        case .geist: return "Geist"
        case .inter: return "Inter"
        }
    }

    var hint: String {
        switch self {
        case .system: return "Apple's San Francisco Pro, the closest match to the ChatGPT iPhone look."
        case .sfRounded: return "Apple's rounded San Francisco variant, softer without losing iOS legibility."
        case .geist: return "Geist for text, with SF Mono for code and identifiers."
        case .inter: return "A clean screen-first sans used widely in modern product interfaces."
        }
    }

    /// The bundled PostScript names, by weight. System-native faces and all
    /// identifier text use the phone's own fonts. Generated by
    /// `npm run build:ios-fonts` and
    /// registered through `UIAppFonts` in `ios/Argmax/project.yml`; a name
    /// that no longer resolves is what `TypographyTests` catches.
    fileprivate func faceName(_ weight: FaceWeight, mono: Bool) -> String? {
        switch self {
        case .system, .sfRounded: return nil
        case .geist:
            return mono ? nil : "Geist-\(weight.faceSuffix)"
        case .inter:
            return mono ? nil : "Inter-\(weight.faceSuffix)"
        }
    }

    var systemDesign: Font.Design? {
        switch self {
        case .sfRounded: return .rounded
        case .system, .geist, .inter: return nil
        }
    }
}

/// The four cuts that ship. The bundled families are static here rather than
/// variable, so a weight in between rounds to the nearest face that exists
/// instead of being synthesised.
fileprivate enum FaceWeight {
    case regular, medium, semibold, bold

    var faceSuffix: String {
        switch self {
        case .regular: return "Regular"
        case .medium: return "Medium"
        case .semibold: return "SemiBold"
        case .bold: return "Bold"
        }
    }

    init(_ weight: Font.Weight) {
        switch weight {
        case .bold, .heavy, .black: self = .bold
        case .semibold: self = .semibold
        case .medium: self = .medium
        default: self = .regular
        }
    }

    init(_ weight: UIFont.Weight) {
        switch weight {
        case .bold, .heavy, .black: self = .bold
        case .semibold: self = .semibold
        case .medium: self = .medium
        default: self = .regular
        }
    }
}

/// The phone's five-step app-wide type scale. The middle step is the current
/// design, and the range stays deliberately narrow so the setting is
/// noticeable without making the layout feel like a different app.
enum AppFontScale: Int, CaseIterable, Identifiable, Sendable {
    case one = 1
    case two
    case three
    case four
    case five

    static let standard = AppFontScale.three

    var id: Int { rawValue }
    var label: String { String(rawValue) }

    var multiplier: CGFloat {
        switch self {
        case .one: return 0.92
        case .two: return 0.96
        case .three: return 1
        case .four: return 1.04
        case .five: return 1.08
        }
    }
}

/// Resolves a role into a font in the chosen typeface.
///
/// Handed down the environment rather than read from `Appearance`, so a view
/// re-draws when the setting changes without observing an object, and every
/// `#Preview` gets the system scale for free.
struct TypeScale: Equatable, Sendable {
    let typeface: AppTypeface
    let fontScale: AppFontScale

    static let system = TypeScale(typeface: .system)

    init(typeface: AppTypeface, fontScale: AppFontScale = .standard) {
        self.typeface = typeface
        self.fontScale = fontScale
    }

    /// A text style, in the chosen face. `weight` defaults to whatever the
    /// system style carries — `.headline` is semibold, everything else
    /// regular — so a call site that names no weight matches SF.
    func font(
        _ style: Font.TextStyle,
        weight: Font.Weight? = nil,
        mono: Bool = false,
        monospacedDigit: Bool = false
    ) -> Font {
        let resolved = weight ?? Self.defaultWeight(style)
        let font = self.font(size: Self.baseSize(style), relativeTo: style, weight: resolved, mono: mono)
        return monospacedDigit ? font.monospacedDigit() : font
    }

    /// A size the design asks for by number, scaled against a text style the
    /// way `@ScaledMetric` scales a measurement. Only for the two places a
    /// role's own size is deliberately between the system's steps.
    ///
    /// `design` is the system's own. A typeface-level system design, such as
    /// SF Rounded, takes precedence when the selected face is system-native.
    func font(
        size: CGFloat,
        relativeTo style: Font.TextStyle,
        weight: Font.Weight = .regular,
        mono: Bool = false,
        design: Font.Design = .default
    ) -> Font {
        let scaledSize = size * fontScale.multiplier
        let face = FaceWeight(weight)
        if let name = typeface.faceName(face, mono: mono) {
            // `relativeTo` is what scales a custom face for Dynamic Type —
            // the size handed in is the one at the Large content size.
            return .custom(name, size: scaledSize, relativeTo: style)
        }
        let scaled = UIFontMetrics(forTextStyle: Self.uiStyle(style)).scaledValue(for: scaledSize)
        let systemDesign = typeface.systemDesign ?? design
        return .system(size: scaled, weight: weight, design: mono ? .monospaced : systemDesign)
    }

    /// The UIKit half, for the one surface drawn by TextKit rather than by
    /// SwiftUI: the diff viewer's code text (`Review/CodeText.swift`).
    func uiFont(
        size: CGFloat,
        relativeTo style: UIFont.TextStyle,
        weight: UIFont.Weight = .regular,
        mono: Bool = false,
        compatibleWith traits: UITraitCollection? = nil
    ) -> UIFont {
        let scaledSize = size * fontScale.multiplier
        let face = FaceWeight(weight)
        let base: UIFont
        if let name = typeface.faceName(face, mono: mono), let custom = UIFont(name: name, size: scaledSize) {
            base = custom
        } else if mono {
            base = .monospacedSystemFont(ofSize: scaledSize, weight: weight)
        } else {
            let system = UIFont.systemFont(ofSize: scaledSize, weight: weight)
            if typeface == .sfRounded,
               let rounded = system.fontDescriptor.withDesign(.rounded)
            {
                base = UIFont(descriptor: rounded, size: scaledSize)
            } else {
                base = system
            }
        }
        return UIFontMetrics(forTextStyle: style).scaledFont(for: base, compatibleWith: traits)
    }

    /// Each text style's size at the Large content size — the numbers iOS
    /// itself uses, so a custom face lands on the same grid as SF and a
    /// screen does not re-flow when the typeface changes.
    static func baseSize(_ style: Font.TextStyle) -> CGFloat {
        switch style {
        case .largeTitle: return 34
        case .title: return 28
        case .title2: return 22
        case .title3: return 20
        case .headline: return 17
        case .body: return 17
        case .callout: return 16
        case .subheadline: return 15
        case .footnote: return 13
        case .caption: return 12
        case .caption2: return 11
        @unknown default: return 17
        }
    }

    /// `.headline` is the one system style that is not regular.
    private static func defaultWeight(_ style: Font.TextStyle) -> Font.Weight {
        style == .headline ? .semibold : .regular
    }

    private static func uiStyle(_ style: Font.TextStyle) -> UIFont.TextStyle {
        switch style {
        case .largeTitle: return .largeTitle
        case .title: return .title1
        case .title2: return .title2
        case .title3: return .title3
        case .headline: return .headline
        case .body: return .body
        case .callout: return .callout
        case .subheadline: return .subheadline
        case .footnote: return .footnote
        case .caption: return .caption1
        case .caption2: return .caption2
        @unknown default: return .body
        }
    }
}

private struct TypeScaleKey: EnvironmentKey {
    static let defaultValue = TypeScale.system
}

extension EnvironmentValues {
    var typeScale: TypeScale {
        get { self[TypeScaleKey.self] }
        set { self[TypeScaleKey.self] = newValue }
    }
}

private struct TypeStyle: ViewModifier {
    @Environment(\.typeScale) private var scale
    let style: Font.TextStyle
    let weight: Font.Weight?
    let mono: Bool
    let monospacedDigit: Bool
    let ink: Color?

    func body(content: Content) -> some View {
        let font = scale.font(style, weight: weight, mono: mono, monospacedDigit: monospacedDigit)
        if let ink {
            content.font(font).foregroundStyle(ink)
        } else {
            content.font(font)
        }
    }
}

private struct TypeSize: ViewModifier {
    @Environment(\.typeScale) private var scale
    let size: CGFloat
    let style: Font.TextStyle
    let weight: Font.Weight
    let mono: Bool
    let design: Font.Design
    let ink: Color?

    func body(content: Content) -> some View {
        let font = scale.font(size: size, relativeTo: style, weight: weight, mono: mono, design: design)
        if let ink {
            content.font(font).foregroundStyle(ink)
        } else {
            content.font(font)
        }
    }
}

extension View {
    /// The whole app's typeface and size, set once at the root.
    func typeScale(_ typeface: AppTypeface, fontScale: AppFontScale = .standard) -> some View {
        environment(\.typeScale, TypeScale(typeface: typeface, fontScale: fontScale))
    }

    /// A text style in the app's typeface: the escape hatch for a one-off the
    /// roles below do not name. `mono` is for identifiers — ids, branches,
    /// paths — which stay monospace in every typeface.
    func typeStyle(
        _ style: Font.TextStyle,
        weight: Font.Weight? = nil,
        mono: Bool = false,
        monospacedDigit: Bool = false,
        ink: Color? = nil
    ) -> some View {
        modifier(TypeStyle(style: style, weight: weight, mono: mono, monospacedDigit: monospacedDigit, ink: ink))
    }

    /// A deliberate point size, scaled against a text style.
    func typeSize(
        _ size: CGFloat,
        relativeTo style: Font.TextStyle,
        weight: Font.Weight = .regular,
        mono: Bool = false,
        design: Font.Design = .default,
        ink: Color? = nil
    ) -> some View {
        modifier(TypeSize(size: size, style: style, weight: weight, mono: mono, design: design, ink: ink))
    }

    /// An SF Symbol's size, which stays on the system face in every
    /// typeface: a symbol is drawn *by* SF, and handing it Geist would size
    /// the glyph off a face that has no glyph for it. Named rather than left
    /// as a bare `.font` so a symbol is an obvious exception instead of a
    /// missed call site.
    func typeSymbol(_ style: Font.TextStyle, weight: Font.Weight = .regular) -> some View {
        font(.system(style).weight(weight))
    }

    /// A symbol at a size the layout depends on — a mark sized to its row
    /// rather than to the text beside it.
    func typeSymbol(size: CGFloat, weight: Font.Weight = .regular) -> some View {
        font(.system(size: size, weight: weight))
    }

    /// Screen titles. We draw our own header, so this is the largest type in
    /// the app — there is no system large title anywhere.
    func typeScreenTitle() -> some View {
        typeStyle(.title2, weight: .semibold, ink: Theme.ink)
    }

    /// A pushed screen's title: inline-sized, the way the platform drops from a
    /// large root title to a compact one once you are a level in.
    func typePushedTitle() -> some View {
        typeStyle(.headline, ink: Theme.ink)
    }

    /// A row's own name, and the one line that must never truncate away.
    ///
    /// 18pt to match the transcript's prose at its phone step (13px + 5), so a
    /// title in the list and the first line of the chat are one size.
    func typeRowTitle() -> some View {
        typeSize(18, relativeTo: .body, ink: Theme.ink)
    }

    /// Body copy inside a screen: help text, a sheet's prompt editor, a
    /// settings row's value.
    func typeContent() -> some View {
        typeStyle(.subheadline, ink: Theme.ink)
    }

    /// Everything around the output: labels, controls, status, counts, names,
    /// second lines. One size, so hierarchy inside it comes from weight and
    /// colour — `typeMeta()` is this size in muted ink.
    func typeChrome() -> some View {
        typeStyle(.footnote, ink: Theme.ink)
    }

    /// The second line of a row, a section heading, a field's help.
    func typeMeta() -> some View {
        typeStyle(.footnote, ink: Theme.muted)
    }

    /// A section heading over a group of rows: the meta size, carrying the
    /// weight that makes it a heading rather than a caption.
    func typeSectionHeading() -> some View {
        typeStyle(.footnote, weight: .semibold, ink: Theme.muted)
    }

    /// Chips, attention capsules, the trailing time column.
    func typeChip() -> some View {
        typeStyle(.caption2, weight: .semibold)
    }
}
