
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthPing(input: HealthPingInput) : Promise<HealthPingOutput> {
    return await TAURI_INVOKE("health_ping", { input });
},
async projectsList(input: ProjectsListInput) : Promise<void> {
    await TAURI_INVOKE("projects_list", { input });
},
async projectsPickFolder(input: ProjectsPickFolderInput) : Promise<void> {
    await TAURI_INVOKE("projects_pick_folder", { input });
},
async dashboardList(input: DashboardListInput) : Promise<void> {
    await TAURI_INVOKE("dashboard_list", { input });
},
async projectsRegister(input: ProjectsRegisterInput) : Promise<void> {
    await TAURI_INVOKE("projects_register", { input });
},
async projectsRemove(input: ProjectsRemoveInput) : Promise<void> {
    await TAURI_INVOKE("projects_remove", { input });
},
async projectsUpdateSettings(input: ProjectsUpdateSettingsInput) : Promise<void> {
    await TAURI_INVOKE("projects_update_settings", { input });
},
async projectsListBranches(input: ProjectsListBranchesInput) : Promise<void> {
    await TAURI_INVOKE("projects_list_branches", { input });
},
async projectsSwitchBranch(input: ProjectsSwitchBranchInput) : Promise<void> {
    await TAURI_INVOKE("projects_switch_branch", { input });
},
async workspacesCreateIsolated(input: WorkspacesCreateIsolatedInput) : Promise<void> {
    await TAURI_INVOKE("workspaces_create_isolated", { input });
},
async workspacesCreateCurrent(input: WorkspacesCreateCurrentInput) : Promise<void> {
    await TAURI_INVOKE("workspaces_create_current", { input });
},
async workspacesRefreshStatus(input: WorkspacesRefreshStatusInput) : Promise<void> {
    await TAURI_INVOKE("workspaces_refresh_status", { input });
},
async workspacesKeep(input: WorkspacesKeepInput) : Promise<void> {
    await TAURI_INVOKE("workspaces_keep", { input });
},
async workspacesArchive(input: WorkspacesArchiveInput) : Promise<void> {
    await TAURI_INVOKE("workspaces_archive", { input });
},
async workspacesOpenInIde(input: WorkspacesOpenInIdeInput) : Promise<void> {
    await TAURI_INVOKE("workspaces_open_in_ide", { input });
},
async workspaceStatus(input: WorkspaceStatusInput) : Promise<void> {
    await TAURI_INVOKE("workspace_status", { input });
},
async providersDiscover(input: ProvidersDiscoverInput) : Promise<void> {
    await TAURI_INVOKE("providers_discover", { input });
},
async providersLaunch(input: ProvidersLaunchInput) : Promise<void> {
    await TAURI_INVOKE("providers_launch", { input });
},
async providersSendInput(input: ProvidersSendInput) : Promise<void> {
    await TAURI_INVOKE("providers_send_input", { input });
},
async providersResize(input: ProvidersResizeInput) : Promise<void> {
    await TAURI_INVOKE("providers_resize", { input });
},
async providersTerminate(input: ProvidersTerminateInput) : Promise<void> {
    await TAURI_INVOKE("providers_terminate", { input });
},
async providersCancelQueuedMessage(input: ProvidersCancelQueuedMessageInput) : Promise<void> {
    await TAURI_INVOKE("providers_cancel_queued_message", { input });
},
async attachmentsSaveImage(input: AttachmentsSaveImageInput) : Promise<void> {
    await TAURI_INVOKE("attachments_save_image", { input });
},
async terminalSpawn(input: TerminalSpawnInput) : Promise<void> {
    await TAURI_INVOKE("terminal_spawn", { input });
},
async terminalWrite(input: TerminalWriteInput) : Promise<void> {
    await TAURI_INVOKE("terminal_write", { input });
},
async terminalResize(input: TerminalResizeInput) : Promise<void> {
    await TAURI_INVOKE("terminal_resize", { input });
},
async terminalTerminate(input: TerminalTerminateInput) : Promise<void> {
    await TAURI_INVOKE("terminal_terminate", { input });
},
async approvalsResolve(input: ApprovalsResolveInput) : Promise<void> {
    await TAURI_INVOKE("approvals_resolve", { input });
},
async approvalsPending(input: ApprovalsPendingInput) : Promise<void> {
    await TAURI_INVOKE("approvals_pending", { input });
},
async sessionEventsSince(input: SessionEventsSinceInput) : Promise<void> {
    await TAURI_INVOKE("session_events_since", { input });
},
async reviewListChangedFiles(input: ReviewListChangedFilesInput) : Promise<void> {
    await TAURI_INVOKE("review_list_changed_files", { input });
},
async reviewLoadDiff(input: ReviewLoadDiffInput) : Promise<void> {
    await TAURI_INVOKE("review_load_diff", { input });
},
async reviewListChangedFilesForProject(input: ReviewListChangedFilesForProjectInput) : Promise<void> {
    await TAURI_INVOKE("review_list_changed_files_for_project", { input });
},
async reviewLoadDiffForProject(input: ReviewLoadDiffForProjectInput) : Promise<void> {
    await TAURI_INVOKE("review_load_diff_for_project", { input });
},
async workspaceListFiles(input: WorkspaceListFilesInput) : Promise<void> {
    await TAURI_INVOKE("workspace_list_files", { input });
},
async workspaceReadFile(input: WorkspaceReadFileInput) : Promise<void> {
    await TAURI_INVOKE("workspace_read_file", { input });
},
async workspaceListFilesForProject(input: WorkspaceListFilesForProjectInput) : Promise<void> {
    await TAURI_INVOKE("workspace_list_files_for_project", { input });
},
async workspaceReadFileForProject(input: WorkspaceReadFileForProjectInput) : Promise<void> {
    await TAURI_INVOKE("workspace_read_file_for_project", { input });
},
async workspaceWriteFile(input: WorkspaceWriteFileInput) : Promise<void> {
    await TAURI_INVOKE("workspace_write_file", { input });
},
async workspaceStatFile(input: WorkspaceStatFileInput) : Promise<void> {
    await TAURI_INVOKE("workspace_stat_file", { input });
},
async workspaceWriteFileForProject(input: WorkspaceWriteFileForProjectInput) : Promise<void> {
    await TAURI_INVOKE("workspace_write_file_for_project", { input });
},
async workspaceStatFileForProject(input: WorkspaceStatFileForProjectInput) : Promise<void> {
    await TAURI_INVOKE("workspace_stat_file_for_project", { input });
},
async workspaceGrepContent(input: WorkspaceGrepContentInput) : Promise<void> {
    await TAURI_INVOKE("workspace_grep_content", { input });
},
async checksRun(input: ChecksRunInput) : Promise<void> {
    await TAURI_INVOKE("checks_run", { input });
},
async checkpointsCreate(input: CheckpointsCreateInput) : Promise<void> {
    await TAURI_INVOKE("checkpoints_create", { input });
},
async dashboardLoad(input: DashboardLoadInput) : Promise<void> {
    await TAURI_INVOKE("dashboard_load", { input });
},
async skillsList(input: SkillsListInput) : Promise<void> {
    await TAURI_INVOKE("skills_list", { input });
},
async systemOpenPath(input: SystemOpenPathInput) : Promise<void> {
    await TAURI_INVOKE("system_open_path", { input });
},
async systemListDetectedIdes(input: SystemListDetectedIdesInput) : Promise<void> {
    await TAURI_INVOKE("system_list_detected_ides", { input });
},
async systemDiagnostics(input: SystemDiagnosticsInput) : Promise<void> {
    await TAURI_INVOKE("system_diagnostics", { input });
},
async systemVacuumDatabase(input: SystemVacuumDatabaseInput) : Promise<void> {
    await TAURI_INVOKE("system_vacuum_database", { input });
},
async systemSetTheme(input: SystemSetThemeInput) : Promise<void> {
    await TAURI_INVOKE("system_set_theme", { input });
},
async mcpList(input: McpListInput) : Promise<void> {
    await TAURI_INVOKE("mcp_list", { input });
},
async mcpAuthStart(input: McpAuthStartInput) : Promise<void> {
    await TAURI_INVOKE("mcp_auth_start", { input });
},
async mcpAuthWrite(input: McpAuthWriteInput) : Promise<void> {
    await TAURI_INVOKE("mcp_auth_write", { input });
},
async mcpAuthResize(input: McpAuthResizeInput) : Promise<void> {
    await TAURI_INVOKE("mcp_auth_resize", { input });
},
async mcpAuthTerminate(input: McpAuthTerminateInput) : Promise<void> {
    await TAURI_INVOKE("mcp_auth_terminate", { input });
},
async sessionCostSummary(input: SessionCostSummaryInput) : Promise<void> {
    await TAURI_INVOKE("session_cost_summary", { input });
},
async learningsList(input: LearningsListInput) : Promise<void> {
    await TAURI_INVOKE("learnings_list", { input });
},
async learningsUpdate(input: LearningsUpdateInput) : Promise<void> {
    await TAURI_INVOKE("learnings_update", { input });
},
async learningsDelete(input: LearningsDeleteInput) : Promise<void> {
    await TAURI_INVOKE("learnings_delete", { input });
},
async sessionSearch(input: SessionSearchInput) : Promise<void> {
    await TAURI_INVOKE("session_search", { input });
},
async workspacesSetPinned(input: WorkspacesSetPinnedInput) : Promise<void> {
    await TAURI_INVOKE("workspaces_set_pinned", { input });
},
async prsListForSession(input: PrsListForSessionInput) : Promise<void> {
    await TAURI_INVOKE("prs_list_for_session", { input });
},
async prsRefresh(input: PrsRefreshInput) : Promise<void> {
    await TAURI_INVOKE("prs_refresh", { input });
},
async gitCommit(input: GitCommitInput) : Promise<void> {
    await TAURI_INVOKE("git_commit", { input });
},
async gitPush(input: GitPushInput) : Promise<void> {
    await TAURI_INVOKE("git_push", { input });
},
async gitCreateBranch(input: GitCreateBranchInput) : Promise<void> {
    await TAURI_INVOKE("git_create_branch", { input });
},
async gitViewOrCreatePr(input: GitViewOrCreatePrInput) : Promise<void> {
    await TAURI_INVOKE("git_view_or_create_pr", { input });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentMode = "auto" | "plan"
export type ApprovalId = string
export type ApprovalResolution = "approved" | "rejected"
export type ApprovalsPendingInput = Record<string, never>
export type ApprovalsResolveInput = { approvalId: ApprovalId; status: ApprovalResolution }
export type AttachmentMimeType = "image/png" | "image/jpeg" | "image/gif" | "image/webp"
export type AttachmentPath = string
export type AttachmentSizeBytes = number
export type AttachmentsSaveImageInput = { sessionId: SessionId; mimeType: AttachmentMimeType; dataBase64: Base64ImageData }
export type Base64ImageData = string
export type BaseRef = string
export type BranchName = string
export type CheckpointsCreateInput = { workspaceId: WorkspaceId; label: NonEmptyString }
export type ChecksRunInput = { workspaceId: WorkspaceId; command: CommandText }
export type CommandText = string
export type ComposerAttachmentInput = { filePath: AttachmentPath; mimeType: AttachmentMimeType; sizeBytes: AttachmentSizeBytes }
export type DashboardListInput = Record<string, never>
export type DashboardLoadInput = Record<string, never>
export type FileContent = string
export type GitCommitInput = { workspaceId: WorkspaceId; message: GitCommitMessage; selectedFiles: RelativePath[] | null }
export type GitCommitMessage = string
export type GitCreateBranchInput = { workspaceId: WorkspaceId; branch: BranchName }
export type GitPushInput = { workspaceId: WorkspaceId }
export type GitViewOrCreatePrInput = { sessionId: SessionId }
export type GrepTargetId = string
export type HealthPingInput = Record<string, never>
export type HealthPingOutput = { ok: boolean; timestamp: string }
export type LearningsDeleteInput = { id: NonEmptyString }
export type LearningsListInput = { projectId: ProjectId; limit: Limit200 | null }
export type LearningsUpdateInput = { id: NonEmptyString; summary: NonEmptyString | null; verified: boolean | null }
export type Limit200 = number
export type McpAuthResizeInput = { sessionId: McpAuthSessionId; cols: TerminalCols; rows: TerminalRows }
export type McpAuthSessionId = string
export type McpAuthStartInput = { cols: TerminalCols; rows: TerminalRows }
export type McpAuthTerminateInput = { sessionId: McpAuthSessionId }
export type McpAuthWriteInput = { sessionId: McpAuthSessionId; data: StreamChunk }
export type McpListInput = Record<string, never>
export type NonEmptyString = string
export type NullableExpectedMtimeMs = number | null
export type OpenIdeChoice = "default" | "vscode" | "cursor" | "windsurf" | "zed" | "terminal" | "iterm"
export type OpenPath = string
export type PermissionMode = "auto-approve" | "ask-each-time"
export type ProjectId = string
export type ProjectSettingsInput = { defaultProvider: ProviderId; defaultModelLabel: NonEmptyString; worktreeLocation: NonEmptyString; setupCommand: string; checkCommands: string[] }
export type ProjectsListBranchesInput = { projectId: ProjectId }
export type ProjectsListInput = Record<string, never>
export type ProjectsPickFolderInput = Record<string, never>
export type ProjectsRegisterInput = { repoPath: RepoPath }
export type ProjectsRemoveInput = { projectId: ProjectId }
export type ProjectsSwitchBranchInput = { projectId: ProjectId; branch: BranchName }
export type ProjectsUpdateSettingsInput = { projectId: ProjectId; settings: ProjectSettingsInput }
export type Prompt = string
export type ProviderId = "claude" | "codex" | "cursor"
export type ProvidersCancelQueuedMessageInput = { sessionId: SessionId; messageId: NonEmptyString }
export type ProvidersDiscoverInput = Record<string, never>
export type ProvidersLaunchInput = { workspaceId: WorkspaceId; provider: ProviderId; prompt: Prompt; modelLabel: NonEmptyString; modelId: NonEmptyString; reasoningEffort: ReasoningEffort | null; agentMode: AgentMode | null; permissionMode: PermissionMode | null; cols: TerminalCols; rows: TerminalRows; attachments: ComposerAttachmentInput[] | null }
export type ProvidersResizeInput = { sessionId: SessionId; cols: TerminalCols; rows: TerminalRows }
export type ProvidersSendInput = { sessionId: SessionId; input: Prompt; modelLabel: NonEmptyString | null; modelId: NonEmptyString | null; reasoningEffort: ReasoningEffort | null; agentMode: AgentMode | null; attachments: ComposerAttachmentInput[] | null }
export type ProvidersTerminateInput = { sessionId: SessionId }
export type PrsListForSessionInput = { sessionId: SessionId }
export type PrsRefreshInput = { sessionId: SessionId }
export type ReasoningEffort = "low" | "medium" | "high" | "xhigh"
export type RelativePath = string
export type RepoPath = string
export type ReviewListChangedFilesForProjectInput = { projectId: ProjectId }
export type ReviewListChangedFilesInput = { workspaceId: WorkspaceId }
export type ReviewLoadDiffForProjectInput = { projectId: ProjectId; filePath: RelativePath | null }
export type ReviewLoadDiffInput = { workspaceId: WorkspaceId; filePath: RelativePath | null }
export type SearchQuery = string
export type SessionCostSummaryInput = { sessionId: SessionId }
export type SessionEventsSinceInput = { sessionId: SessionId; eventCursor: number | null; rawOutputCursor: number | null }
export type SessionId = string
export type SessionSearchInput = { query: SessionSearchQuery; limit: Limit200 | null }
export type SessionSearchQuery = string
export type SkillsListInput = { provider: ProviderId; workspaceId: WorkspaceId | null }
export type StreamChunk = string
export type SystemDiagnosticsInput = Record<string, never>
export type SystemListDetectedIdesInput = Record<string, never>
export type SystemOpenPathInput = { path: OpenPath; cwd: NonEmptyString | null }
export type SystemSetThemeInput = { mode: ThemeMode }
export type SystemVacuumDatabaseInput = Record<string, never>
export type TaskLabel = string
export type TerminalCols = number
export type TerminalId = string
export type TerminalResizeInput = { terminalId: TerminalId; cols: TerminalCols; rows: TerminalRows }
export type TerminalRows = number
export type TerminalSpawnInput = { workspaceId: WorkspaceId; cols: TerminalCols; rows: TerminalRows }
export type TerminalTerminateInput = { terminalId: TerminalId }
export type TerminalWriteInput = { terminalId: TerminalId; data: StreamChunk }
export type ThemeMode = "light" | "dark" | "system"
export type WorkspaceGrepContentInput = { kind: WorkspaceGrepKind; id: GrepTargetId; query: SearchQuery }
export type WorkspaceGrepKind = "workspace" | "project"
export type WorkspaceId = string
export type WorkspaceListFilesForProjectInput = { projectId: ProjectId }
export type WorkspaceListFilesInput = { workspaceId: WorkspaceId }
export type WorkspaceReadFileForProjectInput = { projectId: ProjectId; filePath: RelativePath }
export type WorkspaceReadFileInput = { workspaceId: WorkspaceId; filePath: RelativePath }
export type WorkspaceStatFileForProjectInput = { projectId: ProjectId; filePath: RelativePath }
export type WorkspaceStatFileInput = { workspaceId: WorkspaceId; filePath: RelativePath }
export type WorkspaceStatusInput = { workspaceIds: WorkspaceId[] | null }
export type WorkspaceWriteFileForProjectInput = { projectId: ProjectId; filePath: RelativePath; content: FileContent; expectedMtimeMs: NullableExpectedMtimeMs }
export type WorkspaceWriteFileInput = { workspaceId: WorkspaceId; filePath: RelativePath; content: FileContent; expectedMtimeMs: NullableExpectedMtimeMs }
export type WorkspacesArchiveInput = { workspaceId: WorkspaceId; force: boolean | null }
export type WorkspacesCreateCurrentInput = { projectId: ProjectId; taskLabel: TaskLabel }
export type WorkspacesCreateIsolatedInput = { projectId: ProjectId; taskLabel: TaskLabel; baseRef: BaseRef | null }
export type WorkspacesKeepInput = { workspaceId: WorkspaceId }
export type WorkspacesOpenInIdeInput = { workspaceId: WorkspaceId; ide: OpenIdeChoice }
export type WorkspacesRefreshStatusInput = { workspaceId: WorkspaceId }
export type WorkspacesSetPinnedInput = { workspaceId: WorkspaceId; pinned: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
