// IPC request channel names used by the Tauri bridge. Runtime validation lives
// in Rust input newtypes and command structs; this module is a tiny TypeScript
// type source for renderer calls.

export const IPC_CHANNELS = [
  "health:ping",
  "projects:list",
  "projects:pick-folder",
  "dashboard:list",
  "projects:register",
  "projects:remove",
  "projects:update-settings",
  "projects:list-branches",
  "projects:refresh-branch",
  "projects:switch-branch",
  "workspaces:create-isolated",
  "workspaces:create-current",
  "workspaces:refresh-status",
  "workspaces:keep",
  "workspaces:archive",
  "workspaces:open-in-ide",
  "workspaces:autotitle",
  "workspace:status",
  "providers:discover",
  "providers:launch",
  "providers:send-input",
  "providers:resize",
  "providers:terminate",
  "providers:cancel-queued-message",
  "attachments:save-image",
  "terminal:spawn",
  "terminal:write",
  "terminal:resize",
  "terminal:terminate",
  "approvals:resolve",
  "approvals:pending",
  "session:events-since",
  "session:agent-events",
  "review:list-changed-files",
  "review:load-diff",
  "workspace:list-files",
  "workspace:read-file",
  "workspace:write-file",
  "workspace:stat-file",
  "workspace:grep-content",
  "checks:run",
  "skills:list",
  "system:open-path",
  "system:list-detected-ides",
  "system:diagnostics",
  "system:vacuum-database",
  "system:set-theme",
  "session:cost-summary",
  "learnings:list",
  "learnings:update",
  "learnings:delete",
  "session:search",
  "workspaces:set-pinned",
  "workspaces:set-label",
  "prs:list-for-session",
  "prs:refresh",
  "git:commit",
  "git:push",
  "git:create-branch",
  "git:view-or-create-pr"
] as const;

export type IpcChannel = (typeof IPC_CHANNELS)[number];
